apiVersion: apps/v1
kind: Deployment
metadata:
  name: addressbook-deployment
spec:
  selector:
    matchLabels:
      app: addressbook-project
  replicas: 2 
  template:
    metadata:
      labels:
        app: addressbook-project
    spec:
      containers:
      - name: addressbook-project
        image: yashyash/adressbook:1.0 
        ports:
        - containerPort: 8080
